# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test_stimulation.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1443, 790)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.trigger = QtWidgets.QPushButton(self.centralwidget)
        self.trigger.setGeometry(QtCore.QRect(10, 570, 611, 175))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.trigger.setFont(font)
        self.trigger.setObjectName("trigger")
        self.intensity_minus_1000 = QtWidgets.QPushButton(self.centralwidget)
        self.intensity_minus_1000.setGeometry(QtCore.QRect(10, 390, 300, 175))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.intensity_minus_1000.setFont(font)
        self.intensity_minus_1000.setObjectName("intensity_minus_1000")
        self.intensity_plus_1000 = QtWidgets.QPushButton(self.centralwidget)
        self.intensity_plus_1000.setGeometry(QtCore.QRect(10, 50, 300, 175))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.intensity_plus_1000.setFont(font)
        self.intensity_plus_1000.setObjectName("intensity_plus_1000")
        self.intensity_label = QtWidgets.QLabel(self.centralwidget)
        self.intensity_label.setGeometry(QtCore.QRect(10, 230, 601, 151))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.intensity_label.setFont(font)
        self.intensity_label.setAlignment(QtCore.Qt.AlignCenter)
        self.intensity_label.setObjectName("intensity_label")
        self.unit_label = QtWidgets.QLabel(self.centralwidget)
        self.unit_label.setGeometry(QtCore.QRect(540, 290, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.unit_label.setFont(font)
        self.unit_label.setObjectName("unit_label")
        self.intensity_minus_100 = QtWidgets.QPushButton(self.centralwidget)
        self.intensity_minus_100.setGeometry(QtCore.QRect(320, 390, 300, 175))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.intensity_minus_100.setFont(font)
        self.intensity_minus_100.setObjectName("intensity_minus_100")
        self.intensity_plus_100 = QtWidgets.QPushButton(self.centralwidget)
        self.intensity_plus_100.setGeometry(QtCore.QRect(320, 50, 300, 175))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.intensity_plus_100.setFont(font)
        self.intensity_plus_100.setObjectName("intensity_plus_100")
        self.rc = QtWidgets.QLabel(self.centralwidget)
        self.rc.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.rc.setObjectName("rc")
        self.rc_inc = QtWidgets.QRadioButton(self.centralwidget)
        self.rc_inc.setGeometry(QtCore.QRect(90, 12, 82, 17))
        self.rc_inc.setChecked(True)
        self.rc_inc.setObjectName("rc_inc")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.rc_inc)
        self.rc_dec = QtWidgets.QRadioButton(self.centralwidget)
        self.rc_dec.setGeometry(QtCore.QRect(180, 12, 82, 17))
        self.rc_dec.setObjectName("rc_dec")
        self.buttonGroup.addButton(self.rc_dec)
        self.by = QtWidgets.QLabel(self.centralwidget)
        self.by.setGeometry(QtCore.QRect(270, 10, 81, 21))
        self.by.setObjectName("by")
        self.rc_amount = QtWidgets.QLineEdit(self.centralwidget)
        self.rc_amount.setGeometry(QtCore.QRect(320, 10, 113, 20))
        self.rc_amount.setObjectName("rc_amount")
        self.MplWidget = MplWidget(self.centralwidget)
        self.MplWidget.setGeometry(QtCore.QRect(630, 50, 801, 701))
        self.MplWidget.setObjectName("MplWidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(980, 0, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionIncrease = QtWidgets.QAction(MainWindow)
        self.actionIncrease.setObjectName("actionIncrease")
        self.actionDecrease = QtWidgets.QAction(MainWindow)
        self.actionDecrease.setObjectName("actionDecrease")
        self.action20 = QtWidgets.QAction(MainWindow)
        self.action20.setObjectName("action20")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.trigger.setText(_translate("MainWindow", "Trigger"))
        self.intensity_minus_1000.setText(_translate("MainWindow", "-"))
        self.intensity_plus_1000.setText(_translate("MainWindow", "+"))
        self.intensity_label.setText(_translate("MainWindow", "1000"))
        self.unit_label.setText(_translate("MainWindow", "µA"))
        self.intensity_minus_100.setText(_translate("MainWindow", "-"))
        self.intensity_plus_100.setText(_translate("MainWindow", "+"))
        self.rc.setText(_translate("MainWindow", "Right Click "))
        self.rc_inc.setText(_translate("MainWindow", "increases"))
        self.rc_dec.setText(_translate("MainWindow", "decreases"))
        self.by.setText(_translate("MainWindow", "by"))
        self.rc_amount.setText(_translate("MainWindow", "1000"))
        self.label.setText(_translate("MainWindow", "H-Reflex"))
        self.actionIncrease.setText(_translate("MainWindow", "Increase"))
        self.actionDecrease.setText(_translate("MainWindow", "Decrease"))
        self.action20.setText(_translate("MainWindow", "100"))

from phase_triggered_tms.pre_post.hwave.mplwidget import MplWidget
